name: Deploy Hello World

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  hello-world-image:
    runs-on: ubuntu-latest
    env:
      AWS-ECR-URI: ${{ secrets.AWS_ECR_URI }}
      AWS-REGION: us-east-1
      DOCKER_IMAGE: ${{ env.AWS-ECR-URI }}/app-core
    steps:
      - name: Fetch github repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS-REGION }}
      - name: AWS ECR docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.AWS-ECR-URI }}
      - run: cd src/app-core/
      - run: docker pull ${{ env.AWS-ECR-URI }}/app-core || true
      - run: docker build --file $GITHUB_WORKSPACE/docker/app-core/Dockerfile --cache-from ${{ env.DOCKER_IMAGE }} -t ${{ env.DOCKER_IMAGE }} .
      - run: docker push ${{ env.DOCKER_IMAGE }}